config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :posts, only: %i[show new create] do
    resources :comments, only: :create
    resources :likes, only: %i[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, inverse_of: :category, dependent: :destroy
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  MIN_TITLE_LENGTH = 5
  MAX_TITLE_LENGTH = 255
  MIN_BODY_LENGTH = 200
  MAX_BODY_LENGTH = 4000

  belongs_to :creator, class_name: 'User'
  belongs_to :category
  has_many :comments, class_name: 'PostComment', dependent: :destroy, inverse_of: :post
  has_many :likes, class_name: 'PostLike', dependent: :destroy, inverse_of: :post

  validates :title, :body, presence: true
  validates :title, length: { minimum: MIN_TITLE_LENGTH, maximum: MAX_TITLE_LENGTH }
  validates :body, length: { minimum: MIN_BODY_LENGTH, maximum: MAX_BODY_LENGTH }
end

app/models/post/comment.rb
class Post::Comment < ApplicationRecord
  default_scope { order(created_at: :desc) }

  MIN_CONTENT_LENGTH = 5

  has_ancestry

  belongs_to :post
  belongs_to :user

  validates :content, presence: true,
                      length: {minimum: MIN_CONTENT_LENGTH}

  scope :roots, -> { where(ancestry: '/') }
end

app/models/post/like.rb
class Post::Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  MIN_CONTENT_LENGTH = 5
  MAX_CONTENT_LENGTH = 400

  has_ancestry

  belongs_to :post
  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: MIN_CONTENT_LENGTH, maximum: MAX_CONTENT_LENGTH }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :rememberable,
         :validatable

  has_many :created_posts, class_name: 'Post', foreign_key: :creator_id,
                           inverse_of: :creator, dependent: :destroy
  has_many :comments, class_name: 'PostComment', inverse_of: :user, dependent: :destroy
  has_many :likes, class_name: 'PostLike', inverse_of: :user, dependent: :destroy

  def liked?(like)
    likes.include?(like)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = current_user.comments.build(
      comment_params.merge({ post_id: @post.id })
    )

    if @comment.save
      redirect_to @post, notice: t('.success')
    else
      redirect_to @post, alert: @comment.errors.full_messages.join("\n")
    end
  end

  private

  def comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = @post.likes.build(user_id: current_user.id)

    redirect_to @post if @like.save
  end

  def destroy
    @like = PostLike.find params[:id]

    if @like.user == current_user && @like.delete
      redirect_to @post
    else
      redirect_to @post, alert: t('.alert')
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @posts = Post.includes(:creator, :likes).order(created_at: :desc)
  end

  def show
    @post = Post.eager_load(:category, :creator, :likes, :comments).find(params[:id])
    @like = @post.likes.find_by(user: current_user)
    @new_comment = PostComment.new
    @comments = @post.comments.order(created_at: :desc).eager_load(:user).arrange(order: { id: :desc })
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.created_posts.build(post_params)

    if @post.save
      redirect_to post_url(@post), notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_link_to(name, url, **url_options, &)
    link_to(name, url, { class: 'nav-link link-dark' }.merge(url_options), &)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def link_to_comment(comment)
    link_to I18n.t('.answer'), '#',
            class: 'fs-6 text-decoration-underline text-lowercase',
            role: 'button',
            'aria_controls' => "response_comment-#{comment.id}",
            'aria-expanded' => 'false',
            'data-bs-target' => "#response_comment-#{comment.id}",
            'data-bs-toggle' => 'collapse'
  end

  def path_to_comment(post, comment)
    post_path(post).concat("#comment-#{comment.id}")
  end
end

app/views/comments/_comment.html.slim
.card.mt-2.rounded-0 id="comment-#{comment.id}"
  .card-header.border-0
    = link_to '#', path_to_comment(post, comment), class: 'me-2'
    span.me-2
      = comment.user.email
    span.fs-6.text-muted
      = l(comment.created_at, format: :short)
  .card-body.border-0
    p.card-text
      = comment.content
  - if user_signed_in?
    .card-footer.border-0
      = link_to_comment(comment)
      .ms-2.collapse id="response_comment-#{comment.id}"
        == render 'comments/form', post:, parent: comment
  .ms-4
    - subtree.each do |comment, subtree|
      == render 'comments/comment', comment:, post: @post, subtree:

app/views/comments/_form.html.slim
= simple_form_for @new_comment,
        url: post_comments_path(post),
        class: 'simple_form new_post_comment' do |f|
  - if parent.present?
    = f.input_field :parent_id, as: :hidden, value: parent.id
  = f.input :content, label: false

  = f.button :submit, t('.button'), class: 'btn btn-primary mt-2'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t(:project)
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true

  body.d-flex.flex-column.h-100
    == render 'partials/nav'
    .container.my-4
      == render 'partials/flash'
      == yield

app/views/likes/_like.html.slim
- if user_signed_in?
  - if like.present?
    = link_to post_like_path(post, like), data: { turbo_method: :delete } do
      i.bi.bi-hand-thumbs-up-fill
  - else
    = link_to post_likes_path(post), data: { turbo_method: :post } do
      i.bi.bi-hand-thumbs-up
- else
  i.bi.bi-hand-thumbs-up

app/views/partials/_flash.html.slim
- flash.each do |key, message|
  - role = key == 'alert' ? 'danger' : 'info'
  = content_tag :div, message, class: "alert alert-#{role}", role: 'alert'

app/views/partials/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4'
        = image_tag asset_path('logo.png'), width: 30
    ul.nav.nav-pills
      - if user_signed_in?
        li.nav-item.me-2
          p.nav-link.disabled = current_user.email
        li.nav-item.me-2
          = nav_link_to t(:new_post), new_post_path
        li.nav-item.me-2
          = nav_link_to t(:log_out), destroy_user_session_path, data: { turbo_method: :delete }
      - else
        li.nav-item.me-2
          = nav_link_to t(:log_in), user_session_path
        li.nav-item.me-2
          = nav_link_to t('.sing_up'), new_user_registration_path

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.association :category
    = f.input :body, input_html: { rows: 10 }

  .form-actions
    = f.button :submit, t('.button')

app/views/posts/_post.html.slim
article.col-12
  h1.mb-4.mb-lg-5
    = post.title
  = simple_format(post.body)
  .d-flex.justify-content-between.mt-5
    #post-section
      span.me-2
        = post.creator.email
      span
        = time_ago_in_words(post.created_at)
    #likes-section
      span.me-2
        = post.likes.size
      == render 'likes/like', post:, like:

app/views/posts/_post_card.html.slim
.col-md-12
  .card.mb-3
    .card-body
      h2.h5.card-title
        = link_to post.title, post_path(post), class: 'link-dark text-decoration-none'
      .card-text.mb-2
        = truncate(post.body, length: TEXT_LIMIT)
      .text-right.small.text-muted.mt-auto
        span.me-2
          | #{t('.liked')}:
          =< post.likes.size
        span.me-2
          = time_ago_in_words(post.created_at)
        span
          = post.creator.email

app/views/posts/comments/_comment.html.slim
.card.mt-2.rounded-0 id="comment-#{comment.id}"
  .card-header.border-0
    = link_to '#', path_to_comment(post, comment), class: 'me-2'
    span.me-2
      = comment.user.email
    span.fs-6.text-muted
      = l(comment.created_at, format: :short)
  .card-body.border-0
    p.card-text
      = comment.content
  - if user_signed_in?
    .card-footer.border-0
      = link_to_comment(comment)
      .ms-2.collapse id="response_comment-#{comment.id}"
        == render 'posts/comments/form', post:, parent: comment
  .ms-4
    - subtree.each do |comment, subtree|
      == render 'posts/comments/comment', comment:, post: @post, subtree:

app/views/posts/index.html.slim
h1 = t('.header')

.row
  == render partial: 'post_card', collection: @posts, as: :post

app/views/posts/new.html.slim
h1 = t(:new_post)

== render 'form', post: @post

app/views/posts/show.html.slim
ol.breadcrumb
  li.breadcrumb-item = link_to t('.posts'), root_path
  li.breadcrumb-item.active = @post.category.name.capitalize
== render @post, like: @like

.lead.mt-3#comment-section
  span
    = PostComment.model_name.human(count: @post.comments.size)
    == render 'comments/form', parent: nil, post: @post if user_signed_in?
    - if @post.comments.any?
      - @comments.each do |comment, subtree|
        == render 'comments/comment', comment:, post: @post, subtree: